supergraph:
  # The socket address and port to listen on
  listen: 127.0.0.1:3005
  path: /graphql

health_check:
  listen: 127.0.0.1:3005

#coprocessor:
#  url: http://localhost:3007
#  router:
#    request:
#      body: true
#      headers: true

#rhai:
#  scripts: rhai
#  main: main.rhai

traffic_shaping:
  all:
    deduplicate_query: true

telemetry:
  exporters:
    metrics:
      prometheus:
        enabled: true
        listen: 127.0.0.1:9090
        path: /metrics

wasm:
  base_path: "wasm"
  main: "main.wasm"
